name: CI Comment Trigger

on:
  issue_comment:
    types: [created]

env:
  WORKFLOW_DATA: |
    {
      "icu" : { "check_name": "icu", "workflow_id": "icu.yml" },
      "curl" : { "check_name": "curl", "workflow_id": "curl.yml" },
      "libxml2" : { "check_name": "libxml2", "workflow_id": "libxml2.yml" },
      "zlib" : { "check_name": "zlib", "workflow_id": "zlib.yml" },
      "ci" : { "check_name": "CI", "workflow_id": "ci.yml" },
      "swift-5.3" : { "check_name": "swift-5.3", "workflow_id": "swift-snapshot.yml", "workflow_inputs": ", \"branch-spec\":\"5.3\""},
      "swift-5.4" : { "check_name": "swift-5.4", "workflow_id": "swift-snapshot.yml", "workflow_inputs": ", \"branch-spec\":\"5.4\"" },
      "swift-5.5" : { "check_name": "swift-5.5", "workflow_id": "swift-snapshot.yml", "workflow_inputs": ", \"branch-spec\":\"5.5\"" },
      "swift-main" : { "check_name": "swift-main", "workflow_id": "swift-snapshot.yml", "workflow_inputs": ", \"branch-spec\":\"main\"" }
    }

jobs:
  configure:
    name: Configure Builds

    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/ci ')

    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
      head_sha: ${{ steps.get_pr.outputs.head_sha }}
      head_ref: ${{ steps.get_pr.outputs.head_ref }}

    steps:
      - name: Fetch Pull Request Info
        id: get_pr
        run: |
          set -e
          
          http_code=$(curl -s -o pr.json -w "%{http_code}" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})
          
          if [ "$http_code" != "200" ]; then
            echo "::error::Failed to fetch PR ${{ github.event.issue.number }}"
            exit 1
          fi
          
          HEAD_SHA=$(jq -r '.head.sha' pr.json)
          HEAD_REF=$(jq -r '.head.ref' pr.json)
          
          echo "Head SHA: $HEAD_SHA"
          echo "Head ref: $HEAD_REF"
          
          echo "::set-output name=head_sha::$HEAD_SHA"
          echo "::set-output name=head_ref::$HEAD_REF"

      - name: Set Matrix
        id: set_matrix
        env:
          AUTHOR_ASSOCIATION: ${{ github.event.comment.author_association }}
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          if [ "$AUTHOR_ASSOCIATION" != "COLLABORATOR" ] && [ "$AUTHOR_ASSOCIATION" != "OWNER" ] && [ "$AUTHOR_ASSOCIATION" != "MEMBER" ]; then
            echo "::error::Only collaborators, members or owner could request this action"
            exit 1
          fi
          
          declare -a MATRIX=()
          for COMMENT_TOKEN in $COMMENT_BODY; do
            case "$COMMENT_TOKEN" in
              
              swift-5.3 | swift-5.4 | swift-5.5 | swift-main | icu | curl | libxml2 | zlib | ci)
                MATRIX+=("\"$COMMENT_TOKEN\"")
                ;;
              
              swift-all)
                MATRIX+=("\"swift-5.3\"" "\"swift-5.4\"" "\"swift-5.5\"" "\"swift-main\"")
                ;;
              
              /ci | test)
                ;;
              
              *)
                echo "::warning::Unknown token: $COMMENT_TOKEN"
                ;;
              
            esac
          done
          
          MATRIX=$(echo ${MATRIX[@]} | tr ' ' ',')
          echo "Build matrix: $MATRIX"
          echo "::set-output name=matrix::{\"workflow\":[$MATRIX]}"

  trigger-workflow:
    name: Trigger Workflow

    runs-on: ubuntu-latest
    needs: [configure]

    strategy:
      fail-fast: false
      matrix:
        ${{ fromJSON(needs.configure.outputs.matrix) }}

    steps:
      - name: Create Check Run
        id: create_check
        run: |
          set -e
          
          http_code=$(curl -s -o check.json -w "%{http_code}" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            -X POST https://api.github.com/repos/${{ github.repository }}/check-runs \
            -d '{"name":"${{ fromJSON(env.WORKFLOW_DATA)[matrix.workflow].check_name }}","head_sha":"${{ needs.configure.outputs.head_sha }}"}')
          
          if [ "$http_code" != "201" ]; then
            echo "::error::Failed to create check"
            exit 1
          fi
          
          CHECK_RUN_ID=$(jq -r '.id' check.json)
          
          echo "Check run ID: $CHECK_RUN_ID"
          echo "::set-output name=check_run_id::$CHECK_RUN_ID"

      - name: Trigger Workflow
        run: |
          set -e
          
          http_code=$(curl -s -w "%{http_code}" -H 'Authorization: token ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ fromJSON(env.WORKFLOW_DATA)[matrix.workflow].workflow_id }}/dispatches \
            -d '{"ref":"${{ needs.configure.outputs.head_ref }}","inputs":{"check_run_id":"${{ steps.create_check.outputs.check_run_id }}"${{ fromJSON(env.WORKFLOW_DATA)[matrix.workflow].workflow_inputs }}}}')
          
          if [ "$http_code" != "204" ]; then
            echo "::error::Failed to start workflow"
            exit 1
          fi

      - name: Update Check Run
        if: failure()
        run: |
          set -e
          
          http_code=$(curl -s -o check.json -w "%{http_code}" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            -X PATCH https://api.github.com/repos/${{ github.repository }}/check-runs/${{ steps.create_check.outputs.check_run_id }} \
            -d '{"conclusion":"failure"}')
          
          echo $http_code
          if [ "$http_code" != "200" ]; then
            echo "::error::Failed to update check run"
            exit 1
          fi
